apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    app.kubernetes.io/component: moco-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: moco-controller
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: moco-controller
      labels:
        app.kubernetes.io/component: moco-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: moco-controller
        image: ghcr.io/cybozu-go/moco:latest
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - name: health
          containerPort: 8081
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /grpc-cert
          name: grpc-cert
          readOnly: true
      volumes:
      - name: grpc-cert
        secret:
          defaultMode: 420
          secretName: moco-controller-grpc
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
