# permissions for end users to view mysqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlcluster-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - moco.cybozu.com
  resources:
  - mysqlclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - moco.cybozu.com
  resources:
  - mysqlclusters/status
  verbs:
  - get
