apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../config
images:
  - name: ghcr.io/cybozu-go/moco
    newName: controller
    newTag: dev
patchesStrategicMerge:
  - patch.yaml
