kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  serviceSubnet: "10.0.0.0/16"
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: /mnt/local-path-provisioner
      containerPath: /var/local-path-provisioner
