apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  name: cluster
spec:
  replicas: 1
  podTemplate:
    spec:
      containers:
        - name: mysqld
          image: quay.io/cybozu/mysql:8.0.28
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        resources:
          requests:
            storage: 100Mi
