apiVersion: apps/v1
kind: Deployment
metadata:
  name: moco-controller
  namespace: moco-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: moco-controller
        image: ghcr.io/cybozu-go/moco:latest
        args:
        - --check-interval=5s
        - --backup-image=moco-backup:dev
        env:
        - name: DEBUG_CONTROLLER
          value: "1"
        - name: TEST_NO_JOB_RESOURCE
          value: "1"
