apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ template "moco.fullname" . }}-serving-cert'
  name: mysqlclusters.moco.cybozu.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: '{{ .Release.Namespace }}'
          name: '{{ template "moco.fullname" . }}-webhook-service'
          path: /convert
      conversionReviewVersions:
        - v1
