apiVersion: apps/v1
kind: Deployment
metadata:
  name: moco-controller-manager
  namespace: moco-system
spec:
  template:
    spec:
      containers:
        - name: manager
          command:
            - /moco-controller
            - --conf-init-container-image=ghcr.io/kfyharukz/moco-conf-gen:server-id-2
#            - --conf-init-container-image=quay.io/cybozu/moco-conf-gen:0.2.1
          image: controller:dev
          imagePullPolicy: Never
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
