name: Release
on:
  push:
    tags:
    - 'v*'
env:
  go-version: 1.16
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t moco:dev .
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - run: docker tag moco:dev ghcr.io/cybozu-go/moco:${GITHUB_REF#refs/tags/v}
    - run: docker push ghcr.io/cybozu-go/moco:${GITHUB_REF#refs/tags/v}
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go-version }}
    - run: make release-build
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tagname="${GITHUB_REF#refs/tags/}"
        if echo ${{ github.ref }} | grep -q -e '-'; then prerelease=-p; fi
        gh release create -t "Release $tagname" $prerelease \
          -n "See [CHANGELOG.md](./CHANGELOG.md) for details." \
          "$tagname" build/*
